# Generated by Django 5.1.3 on 2024-11-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
